<?php

$nationalities =
    [
        ["name"=>"Andorra", "code"=>"376" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"United Arab Emirates", "code"=>"971" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Afghanistan", "code"=>"93" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Antigua And Barbuda", "code"=>"1268" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Anguilla", "code"=>"1264" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Albania", "code"=>"355" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Armenia", "code"=>"374" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Netherlands Antilles", "code"=>"599" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Angola", "code"=>"244" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Antarctica", "code"=>"672" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Argentina", "code"=>"54" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"American Samoa", "code"=>"1684" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Austria", "code"=>"43" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Australia", "code"=>"61" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Aruba", "code"=>"297" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Azerbaijan", "code"=>"994" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bosnia And Herzegovina", "code"=>"387" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Barbados", "code"=>"1246" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bangladesh", "code"=>"880" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Belgium", "code"=>"32" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Burkina Faso", "code"=>"226" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bulgaria", "code"=>"359" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bahrain", "code"=>"973" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Burundi", "code"=>"257" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Benin", "code"=>"229" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Barthelemy", "code"=>"590" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bermuda", "code"=>"1441" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Brunei Darussalam", "code"=>"673" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bolivia", "code"=>"591" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Brazil", "code"=>"55" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bahamas", "code"=>"1242" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Bhutan", "code"=>"975" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Botswana", "code"=>"267" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Belarus", "code"=>"375" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Belize", "code"=>"501" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Canada", "code"=>"1" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cocos (keeling) Islands", "code"=>"61" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Congo, The Democratic Republic Of The", "code"=>"243" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Central African Republic", "code"=>"236" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Congo", "code"=>"242" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Switzerland", "code"=>"41" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cote D Ivoire", "code"=>"225" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cook Islands", "code"=>"682" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Chile", "code"=>"56" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cameroon", "code"=>"237" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"China", "code"=>"86" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Colombia", "code"=>"57" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Costa Rica", "code"=>"506" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cuba", "code"=>"53" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cape Verde", "code"=>"238" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Christmas Island", "code"=>"61" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cyprus", "code"=>"357" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Czech Republic", "code"=>"420" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Germany", "code"=>"49" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Djibouti", "code"=>"253" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Denmark", "code"=>"45" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Dominica", "code"=>"1767" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Dominican Republic", "code"=>"1809" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Algeria", "code"=>"213" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Ecuador", "code"=>"593" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Estonia", "code"=>"372" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Egypt", "code"=>"20" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Eritrea", "code"=>"291" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Spain", "code"=>"34" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Ethiopia", "code"=>"251" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Finland", "code"=>"358" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Fiji", "code"=>"679" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Falkland Islands (malvinas)", "code"=>"500" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Micronesia, Federated States Of", "code"=>"691" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Faroe Islands", "code"=>"298" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"France", "code"=>"33" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Gabon", "code"=>"241" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"United Kingdom", "code"=>"44" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Grenada", "code"=>"1473" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Georgia", "code"=>"995" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Ghana", "code"=>"233" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Gibraltar", "code"=>"350" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Greenland", "code"=>"299" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Gambia", "code"=>"220" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Guinea", "code"=>"224" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Equatorial Guinea", "code"=>"240" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Greece", "code"=>"30" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Guatemala", "code"=>"502" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Guam", "code"=>"1671" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Guinea-bissau", "code"=>"245" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Guyana", "code"=>"592" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Hong Kong", "code"=>"852" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Honduras", "code"=>"504" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Croatia", "code"=>"385" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Haiti", "code"=>"509" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Hungary", "code"=>"36" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Indonesia", "code"=>"62" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Ireland", "code"=>"353" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Israel", "code"=>"972" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Isle Of Man", "code"=>"44" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"India", "code"=>"91" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Iraq", "code"=>"964" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Iran, Islamic Republic Of", "code"=>"98" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Iceland", "code"=>"354" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Italy", "code"=>"39" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Jamaica", "code"=>"1876" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Jordan", "code"=>"962" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Japan", "code"=>"81" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kenya", "code"=>"254" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kyrgyzstan", "code"=>"996" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cambodia", "code"=>"855" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kiribati", "code"=>"686" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Comoros", "code"=>"269" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Kitts And Nevis", "code"=>"1869" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Korea Democratic Peoples Republic Of", "code"=>"850" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Korea Republic Of", "code"=>"82" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kuwait", "code"=>"965" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Cayman Islands", "code"=>"1345" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kazakstan", "code"=>"7" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Lao Peoples Democratic Republic", "code"=>"856" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Lebanon", "code"=>"961" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Lucia", "code"=>"1758" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Liechtenstein", "code"=>"423" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Sri Lanka", "code"=>"94" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Liberia", "code"=>"231" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Lesotho", "code"=>"266" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Lithuania", "code"=>"370" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Luxembourg", "code"=>"352" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Latvia", "code"=>"371" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Libyan Arab Jamahiriya", "code"=>"218" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Morocco", "code"=>"212" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Monaco", "code"=>"377" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Moldova, Republic Of", "code"=>"373" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Montenegro", "code"=>"382" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Martin", "code"=>"1599" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Madagascar", "code"=>"261" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Marshall Islands", "code"=>"692" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Macedonia, The Former Yugoslav Republic Of", "code"=>"389" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mali", "code"=>"223" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Myanmar", "code"=>"95" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mongolia", "code"=>"976" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Macau", "code"=>"853" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Northern Mariana Islands", "code"=>"1670" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mauritania", "code"=>"222" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Montserrat", "code"=>"1664" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Malta", "code"=>"356" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mauritius", "code"=>"230" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Maldives", "code"=>"960" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Malawi", "code"=>"265" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mexico", "code"=>"52" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Malaysia", "code"=>"60" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mozambique", "code"=>"258" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Namibia", "code"=>"264" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"New Caledonia", "code"=>"687" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Niger", "code"=>"227" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Nigeria", "code"=>"234" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Nicaragua", "code"=>"505" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Netherlands", "code"=>"31" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Norway", "code"=>"47" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Nepal", "code"=>"977" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Nauru", "code"=>"674" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Niue", "code"=>"683" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"New Zealand", "code"=>"64" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Oman", "code"=>"968" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Panama", "code"=>"507" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Peru", "code"=>"51" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"French Polynesia", "code"=>"689" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Papua New Guinea", "code"=>"675" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Philippines", "code"=>"63" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Pakistan", "code"=>"92" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Poland", "code"=>"48" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Pierre And Miquelon", "code"=>"508" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Pitcairn", "code"=>"870" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Puerto Rico", "code"=>"1" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Portugal", "code"=>"351" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Palau", "code"=>"680" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Paraguay", "code"=>"595" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Qatar", "code"=>"974" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Romania", "code"=>"40" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Serbia", "code"=>"381" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Russian Federation", "code"=>"7" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Rwanda", "code"=>"250" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saudi Arabia", "code"=>"966" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Solomon Islands", "code"=>"677" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Seychelles", "code"=>"248" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Sudan", "code"=>"249" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Sweden", "code"=>"46" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Singapore", "code"=>"65" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Helena", "code"=>"290" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Slovenia", "code"=>"386" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Slovakia", "code"=>"421" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Sierra Leone", "code"=>"232" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"San Marino", "code"=>"378" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Senegal", "code"=>"221" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Somalia", "code"=>"252" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Suriname", "code"=>"597" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Sao Tome And Principe", "code"=>"239" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"El Salvador", "code"=>"503" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Syrian Arab Republic", "code"=>"963" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Swaziland", "code"=>"268" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Turks And Caicos Islands", "code"=>"1649" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Chad", "code"=>"235" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Togo", "code"=>"228" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Thailand", "code"=>"66" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tajikistan", "code"=>"992" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tokelau", "code"=>"690" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Timor-leste", "code"=>"670" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Turkmenistan", "code"=>"993" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tunisia", "code"=>"216" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tonga", "code"=>"676" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Turkey", "code"=>"90" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Trinidad And Tobago", "code"=>"1868" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tuvalu", "code"=>"688" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Taiwan, Province Of China", "code"=>"886" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Tanzania, United Republic Of", "code"=>"255" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Ukraine", "code"=>"380" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Uganda", "code"=>"256" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"United States", "code"=>"1" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Uruguay", "code"=>"598" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Uzbekistan", "code"=>"998" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Holy See (vatican City State)", "code"=>"39" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Saint Vincent And The Grenadines", "code"=>"1784" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Venezuela", "code"=>"58" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Virgin Islands, British", "code"=>"1284" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Virgin Islands, U.s.", "code"=>"1340" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Viet Nam", "code"=>"84" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Vanuatu", "code"=>"678" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Wallis And Futuna", "code"=>"681" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Samoa", "code"=>"685" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Kosovo", "code"=>"381" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Yemen", "code"=>"967" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Mayotte", "code"=>"262" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"South Africa", "code"=>"27" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Zambia", "code"=>"260" , "created_at"=>now(),"updated_at"=>now()],
        ["name"=>"Zimbabwe", "code"=>"263" , "created_at"=>now(),"updated_at"=>now()]

    ];

return $nationalities;